import Head from "next/head";
import Header from "../../components/header";
import Footer from "../../components/footer";
import Background from "../../components/background";

import fs from "fs";
import path from "path";

export default function Expos({ images }) {
  return (
    <div>
      <Head>
        <title>Marc de Krosse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-color.svg" />
        <link rel="stylesheet" href="https://use.typekit.net/qjb8mfi.css" />
      </Head>
      <main className={"relative bg-black overflow-hidden" + (images.length <= 12 ? " h-screen" : "")}>

        <Background />
        <Header />
        <div className="relative mx-auto container">
          <h1 className="text-white font-azo-sans-web text-6xl pb-4">Expos</h1>

          <div className="grid grid-cols-4 gap-8  pb-16">
            {images.map((image, index) => {
              return (
                <>
                  <div className="w-48 h-48 rounded-lg overflow-hidden ">
                    <img
                      src={image.url}
                      className="w-full h-full object-cover"
                    />
                  </div>
                </>
              );
            })}
          </div>
        </div>
        <Footer />
      </main>
    </div>
  );
}

export const getStaticProps = async () => {
  const imagesDirectory = path.join(
    process.cwd(),
    "public",
    "publications",
    "expos"
  );
  const files = await fs.promises.readdir(imagesDirectory);

  const images = files
    .filter((file) => /\.(png|jpe?g|gif|webp)$/i.test(file))
    .map((file) => {
      return {
        name: file,
        url: `/publications/expos/${file}`,
      };
    });

  return {
    props: {
      images,
    },
  };
};
