import Head from "next/head";
import Image from "next/image";
import Header from "../components/header";
import Footer from "../components/footer";
import Lul from "../public/lul.jpg";
import Imaage from "../public/i really nate higgers a lot.png";

export default function About() {
  return (
    <div>
      <Head>
        <title>Marc de Krosse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-color.svg" />
        <link rel="stylesheet" href="https://use.typekit.net/qjb8mfi.css" />
      </Head>
      <main className="bg-black h-screen overflow-hidden">
        <Header />
        <div className="pt-8 pl-16">
          <h1 className="text-white font-10xl text-6xl font-azo-sans-web">
            Over Mij
          </h1>
        </div>
        <div className="grid grid-cols-2 px-16">
          <div ClassName="mt-10">
            <Image src={Lul} width={500} height={300} alt="a" />
          </div>

          <div>
            <h2 className="text-white font-azo-sans-web text-6xl">Over VERA</h2>

            <p className="text-white font-azo-sans-web pt-6 pb-10">
              VERA is hét centrum van underground Popcultuur in Groningen, of
              zoals wij het graag noemen: Club voor de Internationale Pop
              Underground.
              <br />
              We waren vroeger een studentenvereniging en zo kwamen we aan onze
              naam Veri Et Recti Amici (echte en oprechte vrienden).
              <br />
              Tegenwoordig zijn we een volledig uitgeruste concertzaal waar veel
              legendarische bands in hun beginjaren speelden.
              <br />
              Om er een paar te noemen: U2, Joy Division, Simple Minds, Nick
              Cave, Henry Rollins, <br />
              Sonic Youth, Soundgarden, Slayer, Nirvana, The White Stripes, At
              The Drive-in, Mogwai.
            </p>
            <Image src={Imaage} width={453} height={200} alt="a" />
          </div>
        </div>

        <Footer />
      </main>
    </div>
  );
}
