import Head from "next/head";
import Image from "next/image";
import Header from "../components/header";
import Footer from "../components/footer";
import Lul from "../public/lul.jpg";
import Imaage from "../public/afbeelding.jpeg";

export default function About() {
  return (
    <div>
      <Head>
        <title>Marc de Krosse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-color.svg" />
        <link rel="stylesheet" href="https://use.typekit.net/qjb8mfi.css" />
      </Head>
      <main className="bg-black h-screen overflow-hidden">
        <Header />
        <h1 className="text-white font-10xl text-6xl font-azo-sans-web">
          Over Mij
        </h1>
        <div className="grid grid-cols-2 px-20">
          <div>
            <p className="text-white font-azo-sans-web pt-12 pb-10">
              Hallo, ik ben Marc de Krosse. Hier ga ik wat over mezelf
              vertellen. <br /> Ik werk bij VERA, hier maak ik foto&graves en
              filmpje&graves over verschillende bands. <br /> Vera heeft sinds
              2001 een foto-groep.
              <br /> Marc de Krosse zit hier al sinds het begin bij.
              <br /> &graveik sta het liefst met mijn neus op de band. daarom
              fotografeer ik graag kleine concerten.
              <br /> Professionele fotografen moeten bij grote concerten vaak al
              heel snel weg,
              <br /> bij dit soort bands blijf je gewoon de hele optreden.&grave
            </p>
            <Image src={Lul} width={500} height={300} />
          </div>

          <Image src={Imaage} width={300} height={600} />
        </div>
        <Footer />
      </main>
    </div>
  );
}
