import Head from "next/head";
import Footer from "../components/footer";
import Header from "../components/header";

import Image from "next/image";

import GalleryBuilder from "../components/gallerybuilder";
import Slideshow from "../components/slideshow";

import Disk from "../public/music-disk.jpg";

export default function Gallery() {
  const disks = [];

  for (let i = 0; i < 16; i++) {
    disks.push(Disk);
  }

  console.log(disks);

  return (
    <div>
      <Head>
        <title>Marc de Krosse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-color.svg" />
        <link rel="stylesheet" href="https://use.typekit.net/qjb8mfi.css" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
        />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/tw-elements/dist/css/index.min.css"
        />
        <script
          src="https://cdn.jsdelivr.net/npm/tw-elements/dist/js/index.min.js"
          async
        ></script>
      </Head>

      <main className="bg-black overflow-hidden">
        <Header />

        <div className="pt-6 pl-16">
          <h1 className="text-white font-10xl text-6xl font-azo-sans-web">
            Gallerij
          </h1>
        </div>

        <div className="grid grid-cols-4 gap-4">
          {disks.map((value, index) => {
            return (
              <>
                <div className="w-4 h-4"></div>
                <Image
                  src={value.src}
                  alt="disk ${index}"
                  height={200}
                  width={200}
                />
              </>
            );
          })}
        </div>

        <Footer />
      </main>

      <footer></footer>
    </div>
  );
}
