import Head from "next/head";
import Header from "../components/header";
import Footer from "../components/footer";
import Background from "../components/background";
import Gallery from "../components/gallery";

export default function About() {
  return (
    <div>
      <Head>
        <title>Marc de Krosse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-color.svg" />
        <link rel="stylesheet" href="https://use.typekit.net/qjb8mfi.css" />
      </Head>
      <main className="relative bg-black overflow-hidden">
        <Background />
        <Header />

        <div className="relative mx-auto container hide-scrollbar">
          <h1 className="text-white font-azo-sans-web text-6xl pb-4 pt-4">
            Gallery
          </h1>
          <Gallery />
        </div>
        <Footer />
      </main>
    </div>
  );
}
