import Head from "next/head";
import Image from "next/image";
import Background from "../components/background";
import Footer from "../components/footer";

import Header from "../components/header";
import Jumbotron from "../components/jumbotron";
import LatestWorkCard from "../components/latestWorkCard";
import Videos from "../components/videos";



export default function Home() {
  return (
    <div>
      <Head>
        <title>Marc de Krosse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-color.svg" />
        <link rel="stylesheet" href="https://use.typekit.net/qjb8mfi.css" />
      </Head>

      <main className="relative bg-black h-screen overflow-hidden">
        <Background />

        <Header />
        <Jumbotron />

        <div className="relative z-10 container mx-auto flex flex-col md:flex-row gap-64 flex-between justify-between pt-8 h-[60%]">
          <LatestWorkCard />
          <Videos />
        </div>
        
       
        <Footer />
      </main>

      <footer></footer>
    </div>
  );
}
