import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/footer'

import Header from '../components/header'
import Jumbotron from '../components/jumbotron'

// SVG BLOBS
import Blob01 from '../public/blob1.svg'
import Blob02 from '../public/blob2.svg'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Marc de Krosse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-color.svg" />
        <link rel="stylesheet" href="https://use.typekit.net/qjb8mfi.css"/>
      </Head>

      <main className="bg-black h-screen overflow-hidden">
        <Header/>
        <Jumbotron/>
        <Footer/>
      </main>

      <footer>
       
      </footer>
    </div>
  )
}
