import Head from "next/head";
import Background from "../components/background";
import Footer from "../components/footer";
import Header from "../components/header";

import Image from "next/image";

import GalleryBuilder from "../components/gallerybuilder";
import Slideshow from "../components/slideshow";

import Disk from "../public/disk.png";

export default function Photos() {
  const disks = [];

  for (let i = 0; i < 9; i++) {
    disks.push(Disk);
  }

  return (
    <div>
      <Head>
        <title>Marc de Krosse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-color.svg" />
        <link rel="stylesheet" href="https://use.typekit.net/qjb8mfi.css" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
        />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/tw-elements/dist/css/index.min.css"
        />
        <script
          src="https://cdn.jsdelivr.net/npm/tw-elements/dist/js/index.min.js"
          async
        ></script>
      </Head>

      <main className="relative bg-black overflow-hidden h-screen">
        <Background />
        <Header />

        <div className="relative mx-auto container pt-8">
          <div className="pt-6 pl-16">
            <h1 className="text-white font-10xl text-6xl font-azo-sans-web">
              Gallerij
            </h1>
          </div>

          <div className="mx-auto grid grid-cols-3 pt-8 overflow-hidden w-[45%]">
            {disks.map((value, index) => {
              return (
                <>
                  <div className="">
                    <img src={value.src} alt="disk ${index}" />
                  </div>
                </>
              );
            })}
          </div>
        </div>

        <Footer />
      </main>

      <footer></footer>
    </div>
  );
}
