import Head from "next/head";
import Footer from "../components/footer";
import Header from "../components/header";

import Image from "next/image";
export default function Publicaties() {
  return (
    <div>
      <Head>
        <title>Marc de Krosse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-color.svg" />
        <link rel="stylesheet" href="https://use.typekit.net/qjb8mfi.css" />
      </Head>

      <main className="bg-black overflow-hidden">
        <Header />
        <h1 class="text-white text-left pt-32 ml-64">Publicaties</h1>

        <Footer />
      </main>

      <footer></footer>
    </div>
  );
}
