import Head from "next/head";
import Footer from "../components/footer";
import Header from "../components/header";

import Image from "next/image";
export default function Publicaties() {
  return (
    <div>
      <Head>
        <title>Marc de Krosse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-color.svg" />
        <link rel="stylesheet" href="https://use.typekit.net/qjb8mfi.css" />
      </Head>

      <main className="bg-black overflow-hidden">
        <Header />
        <h1 className="text-white text-left pt-32 ml-64 text-4xl">
          Publicaties
        </h1>

        <div class="flex justify-center">
          <a
            href="publicaties/boek"
            class="text-white align-center hover:underline ml-2"
          >
            Boek
          </a>
        </div>

        <div class="flex justify-center">
          <a href="#" class="text-white align-center hover:underline ml-2">
            Social media
          </a>
        </div>

        <div class="flex justify-center">
          <a href="#" class="text-white align-center hover:underline ml-2">
            Vinyls
          </a>
        </div>

        <div class="flex justify-center">
          <a href="#" class="text-white align-center hover:underline ml-2">
            Expos
          </a>
        </div>

        <div class="flex justify-center">
          <a href="#" class="text-white align-center hover:underline ml-2">
            Posters
          </a>
        </div>

        <Footer />
      </main>

      <footer></footer>
    </div>
  );
}
